spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer
            uri: http://localhost:8081
            predicates:
              - Path=/customers/**
          - id: account
            uri: http://localhost:8082
            predicates:
              - Path=/accounts/**
  application:
    name: gateway-service
server:
  port: 8888
